Repository DrN3MESiS/unity-cops-and-robbers-ai, pull requests merged in 2020-09, with the labels that each got.

#1 Updated Scripts and Merged Movement into a single file
  Assets/Resources/Materials/Assasin.mat
  Assets/Resources/Materials/Assasin.mat.meta
  Assets/Resources/Materials/Pedestrian.mat
  Assets/Resources/Materials/Pedestrian.mat.meta
  Assets/Resources/Materials/Player.mat
  Assets/Resources/Materials/Player.mat.meta
  Assets/Resources/Materials/Police.mat
  Assets/Resources/Materials/Police.mat.meta
  Assets/Resources/Materials/Thief.mat
  Assets/Resources/Materials/Thief.mat.meta
  Assets/Resources/Prefabs/BigFloor.prefab
  Assets/Resources/Prefabs/BigFloor.prefab.meta
  Assets/Resources/Prefabs/Entity.prefab
  Assets/Resources/Prefabs/Entity.prefab.meta
  Assets/Resources/Prefabs/HugeFloor.prefab
  Assets/Resources/Prefabs/HugeFloor.prefab.meta
  Assets/Resources/Prefabs/PathFollowPoint.prefab
  Assets/Resources/Prefabs/PathFollowPoint.prefab.meta
  Assets/Scenes/Scene01.unity
  Assets/Scripts/GameControl/GameControlSB.cs
  Assets/Scripts/GameControl/GameControlSB.cs.meta
  Assets/Scripts/GameControl/GlobalMovement.cs
  Assets/Scripts/GameControl/GlobalMovement.cs.meta
  Assets/Scripts/GameControl/Sub-Necessary Scripts.meta
  Assets/Scripts/GameControl/Sub-Necessary Scripts/Point.cs
  Assets/Scripts/GameControl/Sub-Necessary Scripts/Point.cs.meta
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/PlayerMovement.cs
  Assets/Scripts/Player/PlayerMovement.cs.meta
  Assets/Scripts/_Behaviours.meta
  Assets/Scripts/_Behaviours/Arrival Offset.meta
  Assets/Scripts/_Behaviours/Arrival Offset/Arrival_OffsetPursuit.cs
  Assets/Scripts/_Behaviours/Arrival Offset/Arrival_OffsetPursuit.cs.meta
  Assets/Scripts/_Behaviours/Flee.meta
  Assets/Scripts/_Behaviours/Flee/Fleer.cs
  Assets/Scripts/_Behaviours/Flee/Fleer.cs.meta
  Assets/Scripts/_Behaviours/PathFollow.meta
  Assets/Scripts/_Behaviours/PathFollow/GameControlSB.cs
  Assets/Scripts/_Behaviours/PathFollow/GameControlSB.cs.meta
  Assets/Scripts/_Behaviours/PathFollow/moveVelSimple.cs
  Assets/Scripts/_Behaviours/PathFollow/moveVelSimple.cs.meta
  Assets/Scripts/_Behaviours/Pursuit.meta
  Assets/Scripts/_Behaviours/Pursuit/Pursuit.cs
  Assets/Scripts/_Behaviours/Pursuit/Pursuit.cs.meta
  Assets/Scripts/_Behaviours/Seek.meta
  Assets/Scripts/_Behaviours/Seek/Seeker.cs
  Assets/Scripts/_Behaviours/Seek/Seeker.cs.meta
  Assets/Scripts/_Behaviours/Wander.meta
  Assets/Scripts/_Behaviours/Wander/Wander.cs
  Assets/Scripts/_Behaviours/Wander/Wander.cs.meta
  Assets/Scripts/_Behaviours/_DO NOT USE THESE FILES
  Assets/Scripts/_Behaviours/_DO NOT USE THESE FILES.meta
  ProjectSettings/TagManager.asset
Labels: documentation, enhancement

#2 Prefabs
  Assets/Resources/Prefabs/Assassin Variant.prefab
  Assets/Resources/Prefabs/Assassin Variant.prefab.meta
  Assets/Resources/Prefabs/Pedestrian Variant.prefab
  Assets/Resources/Prefabs/Pedestrian Variant.prefab.meta
  Assets/Resources/Prefabs/Police Variant.prefab
  Assets/Resources/Prefabs/Police Variant.prefab.meta
  Assets/Resources/Prefabs/Thief Variant.prefab
  Assets/Resources/Prefabs/Thief Variant.prefab.meta
  Assets/Scenes/Scene01.unity
Labels: enhancement

#3 Fixed Wander and used different vel Vectors
  Assets/Resources/Prefabs/Entity.prefab
  Assets/Scripts/GameControl/GlobalMovement.cs
Labels: bug

#6 Wander and flee added to pedestrian
  Assets/Scripts/GameControl/GlobalMovement.cs
Labels: enhancement

#10 Update GlobalMovement.cs
  Assets/Scripts/GameControl/GlobalMovement.cs
Labels: enhancement

#11 Release V0.9.0
  Assets/Resources/Prefabs/Thief Variant.prefab
  Assets/Resources/Prefabs/diamond.prefab
  Assets/Scenes/Scene01.unity
  Assets/Scripts/GameControl/GameControlSB.cs
  Assets/Scripts/GameControl/GlobalMovement.cs
  Assets/Scripts/GameControl/Sub-Necessary Scripts/Diamonds.cs
  LICENSE
  ProjectSettings/ProjectVersion.txt
Labels: enhancement

#12 Master -> Dev
  Assets/Scripts/Behaviours.meta
Labels: documentation

#15 Release 0.9.9
  Assets/Resources/Prefabs/Entity.prefab
  Assets/Resources/Prefabs/User.prefab
  Assets/Resources/Prefabs/User.prefab.meta
  Assets/Scenes/Scene01.unity
  Assets/Scripts/GameControl/GameControlSB.cs
  Assets/Scripts/GameControl/GlobalMovement.cs
  Assets/Scripts/Player/CameraMovement.cs
  Assets/Scripts/Player/CameraMovement.cs.meta
  Assets/Scripts/Player/PlayerMovement.cs
Labels: documentation

#17 Release 1.0.0
  Assets/Scripts/GameControl/GlobalMovement.cs
Labels: enhancement
